### ISSUE TITLE
Problem with extracting parts of sequences that contain static scenes

### ISSUE THREAD

**Issue by LuckyShrek** [uzh-rpg/E-RAFT#12]
Hi Mathias,
Thank you for publishing this project. It is very helpful.

I am trying to do the data manipulation of the dataset but I found that you have removed some parts manually since they are static. I found that my results for training is not good at all, and I suspect doing something wrong in this truncation part.

My method works as follows:
1) I compare the elements one by one from both lists "file" and "self.timestamps_flow" from class "Sequence".
2) Since I compare after you created "self.timestamps_flow", When I find mismatch between the two lists, I remove the current element from "self.timestamps_flow" then continue deleting elements from it until I find the current element from both lists are equal, and so on.
3) For some sequences, I found that a part at the end of the file should be deleted as well, so I wrote an extra condition that in case that I reach the end of the "file" list, then I delete the rest of elements from "self.timestamps_flow" after that index.  

After applying the above algorithm, I had more than 8000 samples, but you mentioned that they are 7800 samples only. 

I would be grateful if you enlightened me with what might be the problem.

Thanks in advance

**Comment by magehrig** [comment]
Hi @LuckyShrek 

I cannot debug your code from this description. If I were you, I would implement a simpler dataloader from scratch for training on the dataset. You can write me an email, and I can send you a dataloader for training on the dataset that should be easier (less error-prone) to adapt.

**Comment by LuckyShrek** [comment]
That would be great! I will send you an email now with "DSEC dataloader github" as its subject.
Thanks a lot @magehrig

**Comment by Candy-Crusher** [comment]
Hi Mathias! I’m facing a similar issue and was wondering if you could kindly share a DataLoader for training purposes. I’ve also sent you an email with the subject line "DSEC DataLoader GitHub" for reference.

Thank you so much for your help!
