### ISSUE TITLE
MVSEC indoor_flying sequences evaluated?

### ISSUE THREAD

**Issue by HTLeoo** [uzh-rpg/E-RAFT#17]
Hi, @magehrig 
Have you ever trained E-RAFT on outdoor_day2 and evaluated indoor_flying sequences?
It seems that supervised learning may lead to bad generalization on indoor_flying sequences because of the great difference between outdoor_day and indoor_flying data.

**Comment by magehrig** [comment]
Hi @HTLeoo 
We have not done that. The generalization capabilities may be limited given the training set. It's generally a good idea to deploy the model in scenarios close to the training data or use a more general training dataset.
