### ISSUE TITLE
Training E-RAFT using forward and backward groundtruth?

### ISSUE THREAD

**Issue by HTLeoo** [uzh-rpg/E-RAFT#7]
Hi Mathias, 
I want to know that if you use backward optical flow GT for training E-RAFT.

**Comment by magehrig** [comment]
Hi @HTLeoo 

No, we have not used it. In fact, we have not experimented with using it, so I don't know if it improves performance. Feel free to try it out.

**Comment by HTLeoo** [comment]
Thanks a lot
